apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rbac-test
  title: Test
  description: test rbac
  namespace: default
spec:
  type: service
  lifecycle: managed
  owner: user:default/abdo
  owners: 
    - user:default/abdo
  system: tenant
