apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test
  title: Test
  description: test
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Kubernetes Configuration
      required:
        - appName
      properties:
        appName:
          title: App Name
          type: string
          description: Argo AppName

        appNameValidator:
          type: string
          ui:field: ScaffolderFieldValidator
          ui:options:
            watchField: appName
            validationType: api
            apiPath: proxy/k8s/argoproj.io/v1alpha1/namespaces/argo-cd/applications
            jmesPath: "items[?metadata.name == '{{ value }}']"
            errorMessage: "App '{{ value }}' is already in use"


  steps:
    - id: log
      name: Log Parameters
      action: debug:log
      input:
        message: "test"
        